name: note_book_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.1
  rating_dialog: ^2.0.4
  share_plus: ^4.2.0
  sqflite: ^2.3.2
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_native_splash:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#ffffff"
  branding: assets/images/branding.png
  branding_mode: bottom
  # color_dark: "#171717"
  image: assets/images/splash.png
  android_gravity: center

  # flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/branding.png
    - assets/images/splash.png